.only-default: &only-default
  rules:
    # TODO Should replaced to CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED if GitCI_RUNNER_VERSION will upper then 15.2
    - if: ($CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^release\/.*$/ ||
        $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "master" ||
        $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "develop" ||
        $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "main")
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"


.before-script-default: &before-script-default
  cache:
    paths:
      - .cache/pip
  before_script:
    - python -VV
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate
    - pip --cache-dir=.cache/pip --quiet install tox
    - pip install -U pip


.tox-execution-test-script: &tox-execution-test-script
  - python -m site
  - python -m pip install --upgrade pip setuptools wheel
  - python -m pip install --upgrade virtualenv tox


check-installation:
  image: python:3.10
  stage: test
  <<: *only-default
  <<: *before-script-default
  script:
    - pip install --force-reinstall -e "./"
    - m3


lint:
  <<: *before-script-default
  stage: linter
  needs: [ ]
  script:
    - tox -e lint
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      changes:
        - ./**

# Uses in sonar.gitlab-ci.yml
tests-py310:
  <<: *only-default
  <<: *before-script-default
  stage: test
  script:
    - *tox-execution-test-script
    - tox -e py310
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    paths:
      - coverage.xml
      - report.xml
    expire_in: 1 day
    when: always
    reports:
      junit:
        - report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
